# Generated by Django 6.0.6 on 2026-06-27 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('organization_type', models.CharField(choices=[('SCHOOL', 'School'), ('CHURCH', 'Church'), ('COMPANY', 'Company'), ('NGO', 'NGO'), ('ASSOCIATION', 'Association'), ('PROFESSIONAL_BODY', 'Professional Body'), ('OTHER', 'Other')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('plan', models.CharField(choices=[('FREE', 'Free'), ('STANDARD', 'Standard'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=20)),
                ('max_voters', models.IntegerField(default=100)),
                ('max_elections', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='organizatio_slug_5b8b37_idx'), models.Index(fields=['status'], name='organizatio_status_195db0_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_public_results', models.BooleanField(default=False)),
                ('require_voter_verification', models.BooleanField(default=True)),
                ('voting_anonymity', models.BooleanField(default=True)),
                ('max_candidates_per_position', models.IntegerField(default=10)),
                ('require_2fa_for_admins', models.BooleanField(default=False)),
                ('ip_restriction_enabled', models.BooleanField(default=False)),
                ('allowed_ips', models.TextField(blank=True, help_text='Comma-separated IP addresses')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('custom_domain', models.CharField(blank=True, max_length=255)),
                ('primary_color', models.CharField(default='#0066CC', max_length=7)),
                ('secondary_color', models.CharField(default='#004499', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Organization Settings',
                'db_table': 'organization_settings',
            },
        ),
    ]
