# Generated by Django 6.0.6 on 2026-08-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(default='#4F46E5', help_text='Hex color code, e.g. #4F46E5', max_length=7),
        ),
    ]
