# Generated by Django 6.0.6 on 2026-08-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='setup_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='setup_fee_transaction_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
