# Generated by Django 6.0.6 on 2026-08-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_free_results_downloads_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subscription_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
