# Generated by Django 6.0.6 on 2026-08-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_total_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='recipient_account',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='recipient_bank_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='recipient_type',
            field=models.CharField(choices=[('momo', 'Mobile Money'), ('bank', 'Bank Account')], default='momo', max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='transfer_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
