# Generated by Django 6.0.6 on 2026-07-04 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voterrecord',
            name='one_vote_per_voter_per_election',
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voter_records', to='elections.position'),
        ),
        migrations.AddConstraint(
            model_name='voterrecord',
            constraint=models.UniqueConstraint(fields=('voter', 'election', 'position'), name='one_vote_per_voter_per_election_per_position'),
        ),
    ]
