# Generated by Django 6.0.6 on 2026-07-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_remove_voterrecord_one_vote_per_voter_per_election_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
