# Generated by Django 6.0.6 on 2026-08-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_alter_candidate_options_candidate_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='biography_file',
            field=models.FileField(blank=True, null=True, upload_to='candidates/biography/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='manifesto_file',
            field=models.FileField(blank=True, null=True, upload_to='candidates/manifesto/'),
        ),
    ]
