# Generated by Django 6.0.6 on 2026-08-12 00:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_candidate_biography_file_candidate_manifesto_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_link', to='elections.election')),
            ],
        ),
    ]
