# Generated by Django 6.0.6 on 2026-08-17 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_electionsharelink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_paid_voting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='election',
            name='vote_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='VoteTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveIntegerField(default=1)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paystack_reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('organizer_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_transactions', to='elections.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_transactions', to='elections.election')),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vote_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['election', 'status'], name='vote_transa_electio_cc5d4f_idx'), models.Index(fields=['paystack_reference'], name='vote_transa_paystac_69ee0c_idx')],
            },
        ),
    ]
