# Generated by Django 6.0.6 on 2026-08-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_election_is_paid_voting_election_vote_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidVoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveIntegerField(default=1)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.candidate')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='elections.votetransaction')),
            ],
            options={
                'db_table': 'paid_vote_items',
                'ordering': ['id'],
            },
        ),
    ]
