# Generated by Django 6.0.6 on 2026-08-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_paidvoteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
