# Generated by Django 6.0.6 on 2026-08-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_election_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='election_events/'),
        ),
    ]
