# Generated by Django 6.0.6 on 2026-08-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
